---
apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  selector:
    app: backend
    color: green
  ports:
  - name: http
    port: 10000
    targetPort: 5678
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: green-pod
  labels:
    app: backend
    color: green
spec:
  containers:
  - name: backend
    image: hashicorp/http-echo:latest
    imagePullPolicy: IfNotPresent
    args:
    - -text="green backend"
    ports:
    - name: http
      containerPort: 5678
      protocol: TCP
